# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='language',
            field=models.CharField(blank=True, default='en-us', max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='guessed_language',
            field=models.CharField(blank=True, default='en-us', max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='language',
            field=models.CharField(blank=True, default='en-us', max_length=10),
        ),
    ]
