# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 01:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20170904_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('ip', models.GenericIPAddressField()),
                ('enabled', models.BooleanField(default=False)),
                ('codename', models.CharField(default='', max_length=50, unique=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='', max_length=255)),
                ('contact_name', models.CharField(default='', max_length=255)),
                ('contact_email', models.CharField(default='', max_length=255)),
                ('authors', models.TextField(default='')),
                ('license_name', models.CharField(default='', max_length=255)),
                ('license_link', models.CharField(default='', max_length=255)),
                ('copyright_line_text', models.TextField(blank=True, default='')),
                ('copyright_line_link', models.TextField(blank=True, default='')),
                ('update_url', models.CharField(default='', max_length=255)),
                ('forbid_python2', models.BooleanField(default=False)),
                ('forbid_python3', models.BooleanField(default=False)),
                ('version_label', models.CharField(default='1.0.0', max_length=15)),
                ('version_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('requirements_check_script', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
