# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 23:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_attribute_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corpus',
            name='language',
        ),
        migrations.RemoveField(
            model_name='document',
            name='guessed_language',
        ),
        migrations.AddField(
            model_name='document',
            name='corpus',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='application.Corpus'),
            preserve_default=False,
        ),
    ]
