# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-18 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unitexgramlab', '0005_textautomatoncache'),
    ]

    operations = [
        migrations.AddField(
            model_name='textautomatoncache',
            name='dot',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='textautomatoncache',
            name='corpus',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_automaton_rendered', to='unitexgramlab.CorpusProcessed'),
        ),
    ]
