# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-18 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unitexgramlab', '0006_auto_20171118_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textautomatoncache',
            old_name='dot',
            new_name='gv',
        ),
    ]
